project_name: variance

builds:
  - skip: true

snapshot:
  name_template: "{{ .Tag }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

milestones:
  - repo:
      owner: robitx
      name: variance
    close: true
    fail_on_error: false

release:
  github:
    owner: robitx
    name: variance
  prerelease: auto
  name_template: "Variance v{{.Version}}"
