name: Push

on:
  push:
    branches:
      - main

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go:
          - 1.16
          - 1.17
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}
      - uses: golangci/golangci-lint-action@v2
        with:
          skip-go-installation: true

  test:
    name: Test
    needs: lint
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go:
          - 1.16
          - 1.17
        include:
          - go: 1.17
            update-coverage: true
            update-goreportcard: true
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}
      - uses: actions/cache@v2
        with:
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: ${{ runner.os }}-go-
      - name: Test
        run: make test
      - name: Update Coverage
        if: ${{ matrix.update-coverage }}
        uses: codecov/codecov-action@v1
        with:
          fail_ci_if_error: true
      - name: Update Go Report Card
        if: ${{ matrix.update-goreportcard }}
        uses: creekorful/goreportcard-action@v1.0
